# data
dataset: imagenet1k
data_transforms: imagenet1k_mobile
dataset_dir: /home/ubuntu/yang/data/ImageNet/ILSVRC/Data/CLS-LOC
data_loader_workers: 4

# info
num_classes: 74
image_resize: 256
image_size: 224
num_epochs: 50
print_freq: 100

# optimizer
optimizer: sgd
momentum: 0.9
weight_decay: 0.0001
nesterov: True

# lr
lr: 0.01
lr_scheduler: cosine

# model profiling
profiling: [gpu]

#
random_seed: 1995
batch_size: 1024

log_dir: logs/
model: models.mobilenet_v1
reset_parameters: True
width_mult_list: [0.25, 1.0] #, 0.95, 0.9, 0.85, 0.8, 0.75, 0.7, 0.65, 0.6, 0.55, 0.45, 0.4, 0.35, 0.3
width_mult_range: [0.25, 1.0]
resolution_list: [224, 192, 160, 128]
# test pretrained resume
test_only: False
pretrained: ''
resume: ''
