# data
dataset: cifar100

# info
num_classes: 100
image_size: 32
num_epochs: 200
print_freq: 100

# optimizer
optimizer: sgd
momentum: 0.9
weight_decay: 0.0005
nesterov: True

# lr
lr: 0.1
lr_scheduler: cosine

# model profiling
profiling: [gpu]

#
random_seed: 1995
batch_size: 128

log_dir: logs/
model: models.wideresnet
depth: 28
widen_factor: 10
dropoutrate: 0.0
reset_parameters: True
width_mult_list: [0.9, 1.0]
width_mult_range: [0.9, 1.0]
resolution_list: [32, 28, 24, 20]
# test pretrained resume
test_only: False
pretrained: ''
resume: ''
